jobs:
  release:
    if: github.repository == 'jdbc-observations/datasource-proxy'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 8
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish package
      run: ./mvnw --batch-mode deploy -DskipTests=true -Pgithub-ossrh
name: Release to Maven Central (Deploy Snapshot or Stage Release)
on:
  repository_dispatch:
    types: trigger-ga___publish-ossrh.yml
